### ISSUE TITLE
Je kunt je <Title> component nog flexibeler maken

### ISSUE THREAD

**Issue by Robin1224** [TygoWolven/Sprint16-Component-Building-Block#1]
Als je bij je <Title> component ervoor zorgt dat je ook bijvoorbeeld een h3 of h4 kan gebruiken, kun je deze op meer plekken gebruiken.

**Comment by TygoWolven** [comment]
Bedankt voor de tip!

Om dit te realiseren heb ik gebruik gemaakt van de _'if-else statement'_ gecombineerd met `svelte-props` om te bepalen welk heading-level je wilt gebruiken.

````
<script>
  export let headertype = ''
  export let content = ''
  export let color = ''
</script>

{#if headertype === 'h1' }
  <h1 class="title-{color}">
    {content}
  </h1>
{:else if headertype === 'h2' }
  <h2 class="title-{color}">
    {content}
  </h2>
{:else if headertype === 'h3' }
  <h3 class="title-{color}">
    {content}
  </h3>
{/if}
````
