### ISSUE TITLE
Probeer in de <InfiniteSlider> niet twee keer dezelfde HTML te hebben

### ISSUE THREAD

**Issue by Robin1224** [TygoWolven/Sprint16-Component-Building-Block#2]
Je kunt dit beter enhancen, zodat je op bijvoorbeeld screenreaders niet twee keer dezelfde HTML uitgelezen krijgt

**Comment by TygoWolven** [comment]
Ik heb geen oplossing kunnen vinden om mijn `HTML` maar 1 keer te laden. Dit is natuurlijk nadelig voor screenreaders, want die lezen de lijst dan 2 keer op. Maar daar heb ik een oplossing voor gevonden! Zo heb ik het _'aria-hidden: true'_ attribute kunnen meegeven aan de 2e lijst waardoor screenreaders deze overslaan, en de lijst dus maar 1 keer wordt voorgelezen.

````
<script>
  // Adjustable aria-attribute
  export let hidden = ''
</script>

<ul class="logo-container" aria-hidden="{hidden}"> 
    ...
</ul>
````
